name: Run Tests

on: [push]

jobs:
  codecov:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Checkout Submodules
        run: git submodule sync --recursive && git submodule update --init --recursive

      - name: Install GCC 9
        run: |
          sudo apt-get install -qq g++-9
          sudo apt-get install -qq gcc-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 20
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 20
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 20
          sudo update-alternatives --config gcc
          sudo update-alternatives --config g++
          sudo update-alternatives --config gcov

      - name: Build Project
        run: |
          cd ${GITHUB_WORKSPACE}
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make

      - name: Run Tests
        run: |
          cd ${GITHUB_WORKSPACE}/build
          ./tests
